[unstable]
#build-std = ["core", "compiler_builtins", "alloc"]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "./src/aarch64-none-elf.json"
incremental = false

[target."aarch64-none-elf"]
runner = "./scripts/run.sh"
